PreCommit:
  ALL:
    quiet: true
    verify_signatures: false

  MergeConflicts:
    description: 'Checking for unaddressed merge conflicts'
    enabled: true
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "^<<<<<<<[ \t]"]

  RuboCop:
    description: 'Checking Ruby style'
    enabled: true
    problem_on_unmodified_line: ignore
    quiet: true
    on_warn: fail

CommitMsg:
  ALL:
    quiet: true
  CapitalizedSubject:
    description: 'Ensuring commit message subjects are capitalized'
    enabled: false
  EmptyMessage:
    description: 'Prevent empty commit messages'
    enabled: true
  TextWidth:
    description: 'Ensure commit message subjects are <60 chars'
    enabled: true
    description: 'Checking text width'
    max_subject_width: 60
    max_body_width: 1000
