AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Gemfile'
  TargetRubyVersion: 2.4

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: [describe, context, configure]

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-class-vars'
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
