language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
script:
  - bundle exec rake test
notifications:
  slack:
    rooms:
      - 'fastly:hFvhBQKliYl9QAO3VujcrLhe#billy'
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: never
