language: ruby
cache: bundler
before_install: gem install bundler -v '1.11.2'
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
script:
  - bundle exec rake
notifications:
  slack:
    rooms:
      - 'fastly:hFvhBQKliYl9QAO3VujcrLhe#billy'
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: never
